name: APPROVAL-TEST-RELEASE-02

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        options:
          - start
          - pause
          - resume

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

#---------------- Docker
  DOCKERHUB:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'pause' || github.event.inputs.action == 'resume'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: suriyakanth1
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: suriyakanth1/dockerimagebuild:main

#---------------- sonarqube
  SONARQUBE:
    needs: [DOCKERHUB]
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'pause' || github.event.inputs.action == 'resume'
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
    env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://158.220.107.63:9000/

#---------------- VM
  VIRTUAL_MACHINE:
    runs-on: ubuntu-latest
    needs: [SONARQUBE]
    if: github.event.inputs.action != 'pause' || github.event.inputs.action == 'resume'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Linux Server
        run: |
          sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 "docker pull suriyakanth1/dockerimagebuild:main && docker run --rm -p 3000:3000 -d suriyakanth1/dockerimagebuild:main"
