        name: build-21	

        on:
          workflow_dispatch:
          push:
           paths-ignore:
             - '.github/workflows/**'
             - '**/Dockerfile'
             - '**/sonar-project.properties'
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "test#123" ssh -o StrictHostKeyChecking=no user@2002:b912:be4::b912: <<EOF
                                     cd ~/projects/script_test/javaproject/Spring-Boot-main 
                              mvn clean
                              mvn install                  
                   EOF