        name: build-11

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "root@321" ssh -o StrictHostKeyChecking=no root@10.152.5.203 <<EOF
                                   
                   EOF