        name: Build-28-1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "test#123" ssh -o StrictHostKeyChecking=no test@89.30.212.136 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main12
                              mvn clean 
                   EOF