        name: Build-Test-1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: null
                 password: null
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: null/dockerimagebuild:main
            

    #---------------- sonarqube
          SONARQUBE:
            needs: [DOCKERHUB]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: ${{ vars.SONARQUBE_ACCESSTOKEN }}
                SONAR_HOST_URL: ${{ vars.SONARQUBE_URL }}

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [SONARQUBE]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              mvn clean
                              mvn install 
                   EOF

      #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            needs: [BUILD_SCRIPT]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IPADDRESS }} "docker pull null/dockerimagebuild:main && docker run --rm -p 3000:3000 -d null/dockerimagebuild:main"