        name: Build-Test-30-3

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- Build Script
          BUILD_SCRIPT:
            needs: [build]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                   sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 <<EOF
                              cd ~/projects/script_test/javaproject/Spring-Boot-main
                              mvn clean
                              mvn install 
                   EOF
               - name: Copy JAR file to S3
                 run: |
                            # # Install AWS CLI
                            # sudo apt update
                            # sudo apt install -y awscli
                            # # Configure AWS CLI (optional, if not pre-configured)
                            # aws configure set aws_access_key_id YOUR_ACCESS_KEY_ID
                            # aws configure set aws_secret_access_key YOUR_SECRET_ACCESS_KEY
                            # # Copy the JAR file to S3
                            # aws s3 cp /path/to/your/local/jar-file.jar s3://your-s3-bucket-name/path/in/s3/to/your-jar-file.jar
