name: [object Promise]
on:
          workflow_dispatch:

      jobs:
      build:
         name: undefined
         runs-on: ubuntu-latest
         steps:
            - name: Check out the repo
              uses: actions/checkout@v3  
      
undefined