name: Publish Docker image
on:
   workflow_dispatch

jobs:
    sonarqube:
    
      name: SonarQube Integration
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
         with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0
       - name: SonarQube Scan
         uses: sonarsource/sonarqube-scan-action@master
         env:
               SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
               SONAR_HOST_URL: http://158.220.107.63:9000/
       - uses: actions/github-script@v6
         with:
          script: |
            import * as core from '@actions/core';

            const logs = await core.getWorkflowLogs();
            for (const log of logs) {
              console.log(log.text); // Output each log line as text
            }
