        name: main
        on:
            workflow_dispatch:

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
        #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            needs: [build]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 uses: appleboy/ssh-action@master
                 with:
                     host: 158.220.107.63
                     username: root
                     password: ClearC0de20S4  # Storing passwords as secrets is more secure
                     port: 22
                     script: |
                         cd /root/projects/cicdapp/cicd_sample/
                         git pull origin main
                         git status
                         npm install
                         node index.js
                         sleep 10

