        name: ONCOMMIT_DEMO

        on:
          workflow_dispatch:
          push:
           paths-ignore:
             - '.github/workflows/**'
             - '**/Dockerfile'
             - '**/sonar-project.properties'
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- DOCKER
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: devtester2025
                 password: dckr_pat_W9cx0PiYuv_5BgW54h7oBv1viCU
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: devtester2025/cicd_sample:main
            
#------------------JUNIT
          JUNIT:
           needs: [DOCKERHUB]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JUNIT job"
#------------------SELENIUM
          SELENIUM:
           needs: [JUNIT]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an SELENIUM job"
#------------------JMETER
          JMETER:
           needs: [SELENIUM]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JMETER job"