        name: Release_May23

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- sonarqube
          SONARQUBE:
            needs: [build]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
                SONAR_HOST_URL: http://158.220.107.63:9000/

      #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            needs: [SONARQUBE]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 "docker pull ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:dev && docker run --rm -p 3000:3000 -d ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:dev"

        #---------------- Docker
          DOCKERHUB:
           needs: [VIRTUAL_MACHINE]
           runs-on: ubuntu-latest
           environment:
              name: DEVELOPMENT
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKER_ACCESSTOKEN }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:dev