name: test-release1

on:
  push:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repob
        uses: actions/checkout@v3

  VIRTUALMACHINE:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Transfer Application Code
        run: sshpass -p ClearC0de20S4 scp -o StrictHostKeyChecking=no .C:/cicd-node-app/cicd_sample/index.js root@158.220.107.63:~/projects/cicdapp
      - name: Deploy to Linux Server
        uses: appleboy/ssh-action@master  # Assuming you're using a custom action for SSH deployment
        with:
          host: 158.220.107.63
          username: root
          password: ClearC0de20S4  # Storing passwords as secrets is more secure
          port: 22
          script: |
            cd /projects/cicdapp
            git pull
            git status
            npm install --only=prod
            pm2 restart cicdapp
