        name: test-sonar-1

      
    on:
    workflow_dispatch:
    schedule:
      - cron:'5 4 * * *'
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

    #---------------- Sonarqube
          SONARQUBE:
            needs: [build]
            runs-on: ubuntu-latest
            environment:
              name: DEVELOPMENT
            steps:
               - uses: actions/checkout@master
               - name: SonarQube Scan
                 uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: ${{ vars.SONARQUBE_ACCESSTOKEN }}
                SONAR_HOST_URL: ${{ vars.SONARQUBE_URL }}