name: test-release1

on:
  push:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repob
        uses: actions/checkout@v3

  VIRTUALMACHINE:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Transfer Application Code
        run: scp -r ./cicd-node-app/cicd-sample/index.js root@158.220.107.63:~/projects/cicdapp

      - name: Deploy to Linux Server
        uses: appleboy/ssh-action@master
        with:
         host: 158.220.107.63
         username: root
         password: ClearC0de20S4
         script: |
          cd ~/node-github-demo
          git pull origin master
          npm install --production
          pm2 restart node-app
