        name: TEST-15-05

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3 

                - name: DockerHub
                  uses: ./.github/actions/dockerhub.yml

                - name: SonarQube
                  uses: ./.github/actions/sonarqube.yml
