name: test-release1

on:
  push:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repob
        uses: actions/checkout@v3

  VIRTUALMACHINE:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Transfer Files via SCP
        run: scp -r ./cicd-node-app/cicd_sample root@158.220.107.63 ~/projects/cicdapp
