        name: test_build_1

        on:
          workflow_dispatch:
          push:
             
  

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
        #---------------- BUILDSCRIPT
          BUILDSCRIPT:
            runs-on: ubuntu-latest
            needs: [build]
            steps:
            - name: Run PowerShell script
              with:
                 run: |
                     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 date
                 
