        name: test-release1
        on:
         push:
        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3          

        #---------------- VM
          VIRTUALMACHINE:
            runs-on: ubuntu-latest
            needs: [build]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 with:
                   host: 158.220.107.63
                   username: root
                   password: ClearC0de20S4
                   port: 22
                   run: |
                      cd ~/home/danielwetan/apps/node1
                      git pull origin master
                      git status
                      npm install --only=prod
                      pm2 restart node1
                 # run: |
                 #     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 "docker pull suriyakanth1/dockerimagebuild:test && docker run --rm -p 3000:3000 -d suriyakanth1/dockerimagebuild:test"
