name: TEST-APPROVAL-1

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '**/Dockerfile'
      - '**/sonar-project.properties'

obs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  


    #---------------- Orchestration 
          ORCHESTRATION:
            needs: [build]
            runs-on: ubuntu-latest
            timeout-minutes: 1
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: suriyakanth1
                   issue-title: "Orchestration"
                   issue-body: "run_id: ${{ github.run_id }}"
          approvers: suriyakanth1
          issue-title: "Orchestration Part 1 and 2"
          issue-body: "Continuing run_id: ${{ github.run_id }}"
      # Add your steps for part 2 here
