        name: Test_Build_1

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            

        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           environment:
              name: PRODUCTION
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: suriyakanth1
                 password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: suriyakanth1/dockerimagebuild:main
            

    #---------------- BUILD_SCRIPT
          BUILD_SCRIPT:
            needs: [DOCKERHUB]
            runs-on: ubuntu-latest
            steps:
               - name: Run script on the VM
                 run: |
                              sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 <<EOF
                                cat > manifest.txt <<EOL
                                Manifest-Version: 1.0
                                Created-By: Maven Archiver 3.4.0
                                Build-Jdk-Spec: 17
                                Implementation-Title: spring-boot-crud-example-2
                                Implementation-Version: 0.0.1-SNAPSHOT
                                Main-Class: org.springframework.boot.loader.JarLauncher
                                Start-Class: com.javatechie.crud.example.SpringBootCrudExample2Application
                                Spring-Boot-Version: 2.2.4.RELEASE
                                Spring-Boot-Classes: BOOT-INF/classes/
                                Spring-Boot-Lib: BOOT-INF/lib/ 
                                Class-Path: ~/projects/script_test
                                EOL
                                EOF

