
    name: modelpipeline
    
    on:
      push:
    
    jobs:
      build:
         name: github
         runs-on: ubuntu-latest
         steps:
            - name: Check out the repo
              uses: actions/checkout@v3  
    #---------------- Docker
      docker:
        needs : [build]
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: suriyakanth1
                password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
              
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: suriyakanth1/dockerimagebuild
          
            - name: Build and push Docker image
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
      #---------------- sonarqube
      sonarqube:
          needs : [docker]
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
          env:
               SONAR_TOKEN: squ_8c5e7438e05474ebcb879b70892d439619fe4daa
               SONAR_HOST_URL: http://158.220.107.63:9000/
      deploy:
            runs-on: ubuntu-latest
            needs: [sonarqube]
            steps:
              - name: Checkout code
                uses: actions/checkout@v3

              - name: SSH into the linux server
                uses: appleboy/ssh-action@master
                with:
                  host: 158.220.107.63
                  username: root
                  password: ClearC0de20S4
                  port: 22

              - name: Pull Docker Image
                run: docker pull suriyakanth1/dockerimagebuild:test
                env:
                  DOCKER_USERNAME: suriyakanth1
                  DOCKER_PASSWORD: Suriya@1999

              - name: Run Docker Container
                run: |
                   docker run --rm -p 3001:3001 -d suriyakanth1/dockerimagebuild:test
                env:
                  DOCKER_USERNAME: suriyakanth1
                  DOCKER_PASSWORD: Suriya@1999
      
