        name: TEST_JUNIT

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
#------------------JUNIT
          JUNIT:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JUNIT job"