name: TEST-RELEASE-14-01

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      # Add your build steps here

      # Add a step to disable the workflow using GitHub CLI
      - name: Disable workflow
        if: always()
        run: |
          gh workflow run disable -w "${{ github.workflow_id }}" --token "${{ secrets.ACCESS_TOKEN }}" --owner "${{ github.repository_owner }}" --repo "${{ github.repository_name }}"

  DOCKERHUB:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: DEVELOPMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerimagebuild:main
