        name: Test-24-04

        on:
          workflow_dispatch:
  


[object Promise]
[object Promise]

        #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            needs: [SONARQUBE]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 "docker pull suriyakanth1/dockerimagebuild:main && docker run --rm -p 3000:3000 -d suriyakanth1/dockerimagebuild:main"