name: Test_22_3

on:
  workflow_dispatch:

jobs:
  build:
    name: GITHUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

  #---------------- Docker
  DOCKERHUB:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: DEVELOPMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: suriyakanth1
          password: dckr_pat_LSDYW7uqWPPYvQOrLJFEbl7oPjM
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: suriyakanth1/dockerimagebuild:main

  #--------------- BUILDSCRIPT
  BUILDSCRIPT:
    runs-on: ubuntu-latest
    needs: [DOCKERHUB]
    steps:
     - name: Run PowerShell script
       shell: pwsh
       run: |
         $num1 = 20
         $num2 = 30
         $sum = $num1 + $num2
         echo "The sum of $num1 and $num2 is: $sum"
     - name: Run SSH command to print file
       run: |
         sum=$((20+30))
         sshpass -p "ClearC0de20S4" ssh -o StrictHostKeyChecking=no root@158.220.107.63 "echo The sum of $num1 and $num2 is: $sum > ~/projects/script_test/sample.txt"
