        name: Test008

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            


        #---------------- Docker
          DOCKERHUB:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
             - name: Checkout code
               uses: actions/checkout@v2
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
             - name: Login to Docker Hub
               uses: docker/login-action@v2
               with:
                 username: ${{ secrets.SSH_PRIVATE_KEY }}
                 password: ${{ secrets.SSH_PRIVATE_KEY }}
             - name: Build and push
               uses: docker/build-push-action@v5
               with:
                  push: true
                  tags: ${{ secrets.SSH_PRIVATE_KEY }}/dockerimagebuild:main

    #---------------- sonarqube
          SONARQUBE:
            needs: [DOCKERHUB]
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@master
              - name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
            env:
                SONAR_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
                SONAR_HOST_URL: ${{ secrets.SSH_PRIVATE_KEY }}

      #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            needs: [SONARQUBE]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3
               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ${{ secrets.SSH_PRIVATE_KEY }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_PRIVATE_KEY }}@${{ secrets.SSH_PRIVATE_KEY }} "docker pull ${{ secrets.SSH_PRIVATE_KEY }}/dockerimagebuild:main && docker run --rm -p 3000:3000 -d ${{ secrets.SSH_PRIVATE_KEY }}/dockerimagebuild:main"