        name: TEST-15-05

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3 
          Docker:
           name: Docker Build
           runs-on: ubuntu-latest
           needs: build
           steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Run Docker build action 
              uses: ./main/.github/workflows/dockerhub.yml

          
