        name: vm-test-2

        on:                  
          workflow_dispatch:
                             

        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            




        #---------------- VM
          VIRTUAL_MACHINE:
            runs-on: ubuntu-latest
            needs: [build]
            steps:
               - name: Checkout code
                 uses: actions/checkout@v3

               - name: Deploy to Linux Server
                 run: |
                     sshpass -p ClearC0de20S4 ssh -o StrictHostKeyChecking=no root@158.220.107.63 "docker pull root/dockerimagebuild:test && docker run --rm -p 3000:3000 -d root/dockerimagebuild:test"